### ISSUE TITLE
"Failed Download Profile Image"

### ISSUE THREAD

**Issue by diskminus** [user95401/ProfileImage#3]
I have putted my pfp and then submitted on the website but I got this issue
Does anyone knows how to fix this issue?
![image_2024-02-25_143815254](https://github.com/user95401/ProfileImage/assets/112528054/86dcec54-efbd-4292-a6a4-6a18a0e4d397)

**Comment by user95401** [comment]
ur name?

**Comment by user95401** [comment]
im not sure if urlmon can donload that
![image](https://github.com/user95401/ProfileImage/assets/90561697/21586ff2-da31-4bbd-9487-f56c6085016d)

**Comment by diskminus** [comment]
nevermind i solved the issue

**Comment by diskminus** [comment]
thanks btw!
